"use client";

import { isLoggedIn, parseJwt } from ".";
import { LOGIN_COOKIE_KEY, LoginData } from "./util";

export const useLoginData = (): LoginData | undefined => {
    if (typeof document !== "undefined") {
        const cookies = document.cookie.split(";");
        // TODO: Don't rely on this, was generated by chatgpt
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            const [key, value] = cookie.split("=");
            if (key === LOGIN_COOKIE_KEY) {
                const token = decodeURIComponent(value);

                if (token) {
                    return parseJwt(token);
                }
            }
        }
    }
};

export const useIsLoggedIn = () => {
    const data = useLoginData();
    return isLoggedIn(data);
};
